module.exports={
    entry:"./main.js",
    output:{
        path:__dirname,
        filename:"buding.js"
    },
    devtool:"source-map",
    module:{
        loaders:[
            {test:/\.css$/,loader:"style!css!"},
            {test:/\.js$/,loader:"babel"}
        ]
    }
}
